// ============================================================
// fontPairs.ts — Curated dataset of 500 Google Font pairings
// Each pair: { heading, body } — both must be valid Google Fonts
// Organized by visual style/mood for variety
// ============================================================

export interface FontPair {
  heading: string;
  body: string;
  category?: string; // optional mood tag
}

export const fontPairs: FontPair[] = [
  // ── CLASSIC ELEGANCE ──────────────────────────────────────
  { heading: "Playfair Display", body: "Source Sans Pro", category: "classic" },
  { heading: "Cormorant Garamond", body: "Proza Libre", category: "classic" },
  { heading: "EB Garamond", body: "Lato", category: "classic" },
  { heading: "Libre Baskerville", body: "Source Sans Pro", category: "classic" },
  { heading: "Crimson Text", body: "Work Sans", category: "classic" },
  { heading: "Spectral", body: "Karla", category: "classic" },
  { heading: "Playfair Display SC", body: "Alice", category: "classic" },
  { heading: "Cormorant", body: "Jost", category: "classic" },
  { heading: "Libre Caslon Display", body: "Libre Caslon Text", category: "classic" },
  { heading: "Bodoni Moda", body: "Jost", category: "classic" },
  { heading: "DM Serif Display", body: "DM Sans", category: "classic" },
  { heading: "Fraunces", body: "Commissioner", category: "classic" },
  { heading: "Lora", body: "Nunito", category: "classic" },
  { heading: "Merriweather", body: "Inter", category: "classic" },
  { heading: "PT Serif", body: "PT Sans", category: "classic" },
  { heading: "Bitter", body: "Raleway", category: "classic" },
  { heading: "Arvo", body: "Lato", category: "classic" },
  { heading: "Cardo", body: "Josefin Sans", category: "classic" },
  { heading: "Gentium Book Plus", body: "Open Sans", category: "classic" },
  { heading: "Sorts Mill Goudy", body: "Cabin", category: "classic" },

  // ── MODERN CLEAN ──────────────────────────────────────────
  { heading: "Poppins", body: "Open Sans", category: "modern" },
  { heading: "Montserrat", body: "Lato", category: "modern" },
  { heading: "Raleway", body: "Open Sans", category: "modern" },
  { heading: "Nunito", body: "Nunito Sans", category: "modern" },
  { heading: "Rubik", body: "Karla", category: "modern" },
  { heading: "Jost", body: "DM Sans", category: "modern" },
  { heading: "Outfit", body: "Figtree", category: "modern" },
  { heading: "Plus Jakarta Sans", body: "Noto Sans", category: "modern" },
  { heading: "Sora", body: "Mulish", category: "modern" },
  { heading: "Lexend", body: "Lexend Deca", category: "modern" },
  { heading: "Manrope", body: "Noto Sans", category: "modern" },
  { heading: "Urbanist", body: "Karla", category: "modern" },
  { heading: "Figtree", body: "Open Sans", category: "modern" },
  { heading: "DM Sans", body: "DM Mono", category: "modern" },
  { heading: "Epilogue", body: "Mulish", category: "modern" },
  { heading: "Mona Sans", body: "Hubot Sans", category: "modern" },
  { heading: "Albert Sans", body: "Nunito Sans", category: "modern" },
  { heading: "Be Vietnam Pro", body: "Lato", category: "modern" },
  { heading: "Josefin Sans", body: "Josefin Slab", category: "modern" },
  { heading: "Cabin", body: "Cabin Condensed", category: "modern" },

  // ── GEOMETRIC BOLD ────────────────────────────────────────
  { heading: "Oswald", body: "Nunito", category: "bold" },
  { heading: "Bebas Neue", body: "Source Sans Pro", category: "bold" },
  { heading: "Barlow Condensed", body: "Barlow", category: "bold" },
  { heading: "Fjalla One", body: "Average", category: "bold" },
  { heading: "Anton", body: "Roboto", category: "bold" },
  { heading: "Black Han Sans", body: "Nanum Gothic", category: "bold" },
  { heading: "Encode Sans Condensed", body: "Encode Sans", category: "bold" },
  { heading: "Exo 2", body: "Hind Siliguri", category: "bold" },
  { heading: "Saira Condensed", body: "Saira", category: "bold" },
  { heading: "Changa", body: "Almarai", category: "bold" },
  { heading: "Teko", body: "Hind", category: "bold" },
  { heading: "Yanone Kaffeesatz", body: "Droid Sans", category: "bold" },
  { heading: "Archivo Black", body: "Archivo", category: "bold" },
  { heading: "Six Caps", body: "Roboto Condensed", category: "bold" },
  { heading: "Barlow Semi Condensed", body: "Barlow", category: "bold" },
  { heading: "Michroma", body: "Rajdhani", category: "bold" },
  { heading: "Squada One", body: "Convergence", category: "bold" },
  { heading: "Saira Semi Condensed", body: "Roboto", category: "bold" },
  { heading: "Russo One", body: "Roboto Condensed", category: "bold" },
  { heading: "Kanit", body: "Prompt", category: "bold" },

  // ── HUMANIST / FRIENDLY ───────────────────────────────────
  { heading: "Nunito", body: "Mulish", category: "friendly" },
  { heading: "Fredoka One", body: "Nunito", category: "friendly" },
  { heading: "Quicksand", body: "Questrial", category: "friendly" },
  { heading: "Varela Round", body: "Varela", category: "friendly" },
  { heading: "Comfortaa", body: "Lato", category: "friendly" },
  { heading: "Pacifico", body: "Open Sans", category: "friendly" },
  { heading: "Righteous", body: "Raleway", category: "friendly" },
  { heading: "Baloo 2", body: "Mukta", category: "friendly" },
  { heading: "Kodchasan", body: "Kanit", category: "friendly" },
  { heading: "Acme", body: "Oxygen", category: "friendly" },
  { heading: "Calistoga", body: "Lato", category: "friendly" },
  { heading: "Fugaz One", body: "Source Sans Pro", category: "friendly" },
  { heading: "Lilita One", body: "Open Sans", category: "friendly" },
  { heading: "Titan One", body: "Lato", category: "friendly" },
  { heading: "Boogaloo", body: "Overpass", category: "friendly" },
  { heading: "Lobster Two", body: "Cabin", category: "friendly" },
  { heading: "Courgette", body: "Raleway", category: "friendly" },
  { heading: "Kalam", body: "Poppins", category: "friendly" },
  { heading: "Amatic SC", body: "Josefin Slab", category: "friendly" },
  { heading: "Satisfy", body: "Open Sans", category: "friendly" },

  // ── TECH / FUTURISTIC ─────────────────────────────────────
  { heading: "Space Grotesk", body: "Space Mono", category: "tech" },
  { heading: "Exo 2", body: "Roboto Mono", category: "tech" },
  { heading: "Titillium Web", body: "Source Code Pro", category: "tech" },
  { heading: "Share Tech Mono", body: "Share Tech", category: "tech" },
  { heading: "Orbitron", body: "Electrolize", category: "tech" },
  { heading: "Rajdhani", body: "Open Sans", category: "tech" },
  { heading: "Syncopate", body: "Oxygen", category: "tech" },
  { heading: "Audiowide", body: "Titillium Web", category: "tech" },
  { heading: "Gemunu Libre", body: "Roboto", category: "tech" },
  { heading: "Chakra Petch", body: "Prompt", category: "tech" },
  { heading: "Aldrich", body: "Roboto Condensed", category: "tech" },
  { heading: "Gruppo", body: "Convergence", category: "tech" },
  { heading: "Iceland", body: "Abel", category: "tech" },
  { heading: "Play", body: "Noto Sans", category: "tech" },
  { heading: "Saira", body: "Source Code Pro", category: "tech" },
  { heading: "Nova Square", body: "Roboto", category: "tech" },
  { heading: "Rationale", body: "Raleway", category: "tech" },
  { heading: "Major Mono Display", body: "Major Mono Display", category: "tech" },
  { heading: "Bungee", body: "Roboto Condensed", category: "tech" },
  { heading: "VT323", body: "Ubuntu Mono", category: "tech" },

  // ── EDITORIAL / MAGAZINE ──────────────────────────────────
  { heading: "Abril Fatface", body: "Lato", category: "editorial" },
  { heading: "Alfa Slab One", body: "Roboto", category: "editorial" },
  { heading: "Passion One", body: "Roboto", category: "editorial" },
  { heading: "Ultra", body: "Slabo 27px", category: "editorial" },
  { heading: "Domine", body: "Open Sans", category: "editorial" },
  { heading: "Suranna", body: "Open Sans", category: "editorial" },
  { heading: "Playfair Display", body: "Fauna One", category: "editorial" },
  { heading: "Yeseva One", body: "Josefin Sans", category: "editorial" },
  { heading: "Unna", body: "Raleway", category: "editorial" },
  { heading: "Vesper Libre", body: "Kumar One Outline", category: "editorial" },
  { heading: "Inknut Antiqua", body: "Work Sans", category: "editorial" },
  { heading: "Pridi", body: "Fira Sans", category: "editorial" },
  { heading: "Rozha One", body: "Harmattan", category: "editorial" },
  { heading: "BioRhyme", body: "Space Mono", category: "editorial" },
  { heading: "Rufina", body: "Sintony", category: "editorial" },
  { heading: "Elsie", body: "Lato", category: "editorial" },
  { heading: "Supermercado One", body: "Nunito", category: "editorial" },
  { heading: "Nixie One", body: "Ledger", category: "editorial" },
  { heading: "Philosopher", body: "Muli", category: "editorial" },
  { heading: "Vidaloka", body: "Nunito", category: "editorial" },

  // ── MINIMAL / REFINED ─────────────────────────────────────
  { heading: "Work Sans", body: "Work Sans", category: "minimal" },
  { heading: "IBM Plex Serif", body: "IBM Plex Sans", category: "minimal" },
  { heading: "Mulish", body: "Mulish", category: "minimal" },
  { heading: "Karla", body: "Lora", category: "minimal" },
  { heading: "Fira Sans", body: "Fira Mono", category: "minimal" },
  { heading: "Source Serif 4", body: "Source Sans 3", category: "minimal" },
  { heading: "Noto Serif", body: "Noto Sans", category: "minimal" },
  { heading: "Lato", body: "Merriweather", category: "minimal" },
  { heading: "Open Sans", body: "Merriweather", category: "minimal" },
  { heading: "Roboto", body: "Roboto Slab", category: "minimal" },
  { heading: "Ubuntu", body: "Ubuntu Mono", category: "minimal" },
  { heading: "Oxygen", body: "Oxygen Mono", category: "minimal" },
  { heading: "Droid Sans", body: "Droid Serif", category: "minimal" },
  { heading: "Cantarell", body: "Lora", category: "minimal" },
  { heading: "Muli", body: "Muli", category: "minimal" },
  { heading: "Roboto Condensed", body: "Roboto", category: "minimal" },
  { heading: "Nanum Gothic", body: "Nanum Myeongjo", category: "minimal" },
  { heading: "Barlow", body: "Barlow Condensed", category: "minimal" },
  { heading: "Overpass", body: "Overpass Mono", category: "minimal" },
  { heading: "Istok Web", body: "Lora", category: "minimal" },

  // ── DISPLAY / STATEMENT ───────────────────────────────────
  { heading: "Lobster", body: "Cabin", category: "display" },
  { heading: "Dancing Script", body: "Josefin Sans", category: "display" },
  { heading: "Sacramento", body: "Alice", category: "display" },
  { heading: "Great Vibes", body: "Raleway", category: "display" },
  { heading: "Tangerine", body: "Josefin Slab", category: "display" },
  { heading: "Yellowtail", body: "Open Sans", category: "display" },
  { heading: "Kaushan Script", body: "Pathway Gothic One", category: "display" },
  { heading: "Pinyon Script", body: "EB Garamond", category: "display" },
  { heading: "Clicker Script", body: "Lato", category: "display" },
  { heading: "Alex Brush", body: "Source Sans Pro", category: "display" },
  { heading: "Euphoria Script", body: "Josefin Sans", category: "display" },
  { heading: "Italianno", body: "Roboto", category: "display" },
  { heading: "Allura", body: "Open Sans", category: "display" },
  { heading: "Norican", body: "Raleway", category: "display" },
  { heading: "Herr Von Muellerhoff", body: "Roboto", category: "display" },
  { heading: "Ruthie", body: "Lato", category: "display" },
  { heading: "Rouge Script", body: "Josefin Sans", category: "display" },
  { heading: "Qwigley", body: "Raleway", category: "display" },
  { heading: "Niconne", body: "Open Sans", category: "display" },
  { heading: "Merienda", body: "Nunito", category: "display" },

  // ── SLAB SERIF ────────────────────────────────────────────
  { heading: "Roboto Slab", body: "Roboto", category: "slab" },
  { heading: "Zilla Slab", body: "Fira Sans", category: "slab" },
  { heading: "Josefin Slab", body: "Josefin Sans", category: "slab" },
  { heading: "Arvo", body: "Nunito", category: "slab" },
  { heading: "Rockwell", body: "Source Sans Pro", category: "slab" },
  { heading: "Glegoo", body: "Poppins", category: "slab" },
  { heading: "Laila", body: "Open Sans", category: "slab" },
  { heading: "Noto Serif", body: "Noto Sans", category: "slab" },
  { heading: "Rokkitt", body: "Raleway", category: "slab" },
  { heading: "Coustard", body: "Lato", category: "slab" },
  { heading: "Patua One", body: "Muli", category: "slab" },
  { heading: "Buenard", body: "Open Sans", category: "slab" },
  { heading: "Artifika", body: "Lato", category: "slab" },
  { heading: "Enriqueta", body: "Nunito", category: "slab" },
  { heading: "Expo M", body: "Source Serif 4", category: "slab" },
  { heading: "Sanchez", body: "Raleway", category: "slab" },
  { heading: "Slabo 27px", body: "Lato", category: "slab" },
  { heading: "Eczar", body: "Gentium Basic", category: "slab" },
  { heading: "Kameron", body: "Hind", category: "slab" },
  { heading: "Kreon", body: "Open Sans", category: "slab" },

  // ── CONDENSED / NARROW ────────────────────────────────────
  { heading: "Roboto Condensed", body: "Roboto Light", category: "condensed" },
  { heading: "Oswald", body: "EB Garamond", category: "condensed" },
  { heading: "Barlow Condensed", body: "Karla", category: "condensed" },
  { heading: "Pathway Gothic One", body: "Average", category: "condensed" },
  { heading: "Days One", body: "Open Sans", category: "condensed" },
  { heading: "Jockey One", body: "Raleway", category: "condensed" },
  { heading: "Ruda", body: "Open Sans", category: "condensed" },
  { heading: "Contrail One", body: "Muli", category: "condensed" },
  { heading: "Damion", body: "Roboto", category: "condensed" },
  { heading: "Black Ops One", body: "Titillium Web", category: "condensed" },
  { heading: "Nova Slim", body: "Lato", category: "condensed" },
  { heading: "Permanent Marker", body: "Open Sans", category: "condensed" },
  { heading: "Boogaloo", body: "Open Sans", category: "condensed" },
  { heading: "Bangers", body: "Open Sans", category: "condensed" },
  { heading: "Sedgwick Ave Display", body: "Lato", category: "condensed" },
  { heading: "Stint Ultra Condensed", body: "Open Sans", category: "condensed" },
  { heading: "Pirata One", body: "Roboto Mono", category: "condensed" },
  { heading: "Share", body: "Share Tech", category: "condensed" },
  { heading: "Dorsa", body: "Raleway", category: "condensed" },
  { heading: "Covered By Your Grace", body: "Source Sans Pro", category: "condensed" },

  // ── WARM / ORGANIC ────────────────────────────────────────
  { heading: "Lora", body: "Source Sans Pro", category: "warm" },
  { heading: "Vollkorn", body: "Muli", category: "warm" },
  { heading: "Alegreya", body: "Lato", category: "warm" },
  { heading: "Alegreya Sans", body: "Alegreya", category: "warm" },
  { heading: "Faustina", body: "Muli", category: "warm" },
  { heading: "Neuton", body: "Cabin", category: "warm" },
  { heading: "Gelasio", body: "Open Sans", category: "warm" },
  { heading: "Stoke", body: "Lato", category: "warm" },
  { heading: "Linden Hill", body: "Raleway", category: "warm" },
  { heading: "Cinzel Decorative", body: "Fauna One", category: "warm" },
  { heading: "Lustria", body: "Lato", category: "warm" },
  { heading: "Macondo", body: "Lato", category: "warm" },
  { heading: "Halant", body: "Dosis", category: "warm" },
  { heading: "Arapey", body: "Lato", category: "warm" },
  { heading: "Gilda Display", body: "Cabin", category: "warm" },
  { heading: "Della Respira", body: "Open Sans", category: "warm" },
  { heading: "Bubblegum Sans", body: "Open Sans", category: "warm" },
  { heading: "Trocchi", body: "Raleway", category: "warm" },
  { heading: "Oranienbaum", body: "Lato", category: "warm" },
  { heading: "Coustard", body: "Open Sans", category: "warm" },

  // ── CREATIVE / ARTISTIC ───────────────────────────────────
  { heading: "Cinzel", body: "Fauna One", category: "artistic" },
  { heading: "Philosopher", body: "Fanwood Text", category: "artistic" },
  { heading: "Forum", body: "Raleway", category: "artistic" },
  { heading: "Marcellus SC", body: "Lato", category: "artistic" },
  { heading: "Uncial Antiqua", body: "Source Serif 4", category: "artistic" },
  { heading: "Caesar Dressing", body: "Lato", category: "artistic" },
  { heading: "Cinzel Decorative", body: "Raleway", category: "artistic" },
  { heading: "IM Fell DW Pica", body: "Raleway", category: "artistic" },
  { heading: "Palatino Linotype", body: "Lato", category: "artistic" },
  { heading: "GFS Didot", body: "GFS Neohellenic", category: "artistic" },
  { heading: "Artifika", body: "Raleway", category: "artistic" },
  { heading: "Adamina", body: "Raleway", category: "artistic" },
  { heading: "Quando", body: "Raleway", category: "artistic" },
  { heading: "Judson", body: "Dosis", category: "artistic" },
  { heading: "Alike", body: "Lato", category: "artistic" },
  { heading: "Alike Angular", body: "Lato", category: "artistic" },
  { heading: "Angkor", body: "Lato", category: "artistic" },
  { heading: "Ovo", body: "Lato", category: "artistic" },
  { heading: "Molle", body: "Raleway", category: "artistic" },
  { heading: "Headland One", body: "Raleway", category: "artistic" },

  // ── INTERNATIONAL / MULTI-SCRIPT ─────────────────────────
  { heading: "Noto Serif JP", body: "Noto Sans JP", category: "international" },
  { heading: "Noto Serif KR", body: "Noto Sans KR", category: "international" },
  { heading: "Noto Serif SC", body: "Noto Sans SC", category: "international" },
  { heading: "IBM Plex Sans Arabic", body: "Cairo", category: "international" },
  { heading: "Scheherazade New", body: "Noto Kufi Arabic", category: "international" },
  { heading: "Amiri Quran", body: "Amiri", category: "international" },
  { heading: "Mirza", body: "Asap", category: "international" },
  { heading: "Literata", body: "Source Sans Pro", category: "international" },
  { heading: "Noto Serif Ethiopic", body: "Noto Sans Ethiopic", category: "international" },
  { heading: "Tiro Devanagari Hindi", body: "Hind", category: "international" },

  // ── MONOSPACE / CODE ──────────────────────────────────────
  { heading: "Fira Code", body: "Fira Sans", category: "code" },
  { heading: "Source Code Pro", body: "Source Sans Pro", category: "code" },
  { heading: "Inconsolata", body: "Raleway", category: "code" },
  { heading: "Space Mono", body: "Space Grotesk", category: "code" },
  { heading: "Roboto Mono", body: "Roboto", category: "code" },
  { heading: "Ubuntu Mono", body: "Ubuntu", category: "code" },
  { heading: "Courier Prime", body: "Karla", category: "code" },
  { heading: "Anonymous Pro", body: "Lato", category: "code" },
  { heading: "Cutive Mono", body: "Cutive", category: "code" },
  { heading: "Nova Mono", body: "Nova Round", category: "code" },

  // ── ADDITIONAL PREMIUM PAIRS ─────────────────────────────
  { heading: "Tenor Sans", body: "Raleway", category: "premium" },
  { heading: "Fanwood Text", body: "Josefin Sans", category: "premium" },
  { heading: "Fauna One", body: "Lato", category: "premium" },
  { heading: "Amethysta", body: "Raleway", category: "premium" },
  { heading: "Amaranth", body: "Open Sans", category: "premium" },
  { heading: "Amita", body: "Lato", category: "premium" },
  { heading: "Antic Slab", body: "Raleway", category: "premium" },
  { heading: "Raleway Dots", body: "Raleway", category: "premium" },
  { heading: "Quantico", body: "Raleway", category: "premium" },
  { heading: "Questrial", body: "Open Sans", category: "premium" },
  { heading: "Rhodium Libre", body: "Raleway", category: "premium" },
  { heading: "Rozha One", body: "Lato", category: "premium" },
  { heading: "Ruda", body: "Lato", category: "premium" },
  { heading: "Rye", body: "Cabin", category: "premium" },
  { heading: "Sahitya", body: "Lato", category: "premium" },
  { heading: "Sail", body: "Lato", category: "premium" },
  { heading: "Salsa", body: "Cabin", category: "premium" },
  { heading: "Sancreek", body: "Raleway", category: "premium" },
  { heading: "Sarina", body: "Lato", category: "premium" },
  { heading: "Sarala", body: "Lato", category: "premium" },
  { heading: "Sawarabi Gothic", body: "Noto Sans JP", category: "premium" },
  { heading: "Scada", body: "Open Sans", category: "premium" },
  { heading: "Scheherazade New", body: "Lato", category: "premium" },
  { heading: "Seaweed Script", body: "Open Sans", category: "premium" },
  { heading: "Secular One", body: "Heebo", category: "premium" },
  { heading: "Sevillana", body: "Lato", category: "premium" },
  { heading: "Siemreap", body: "Lato", category: "premium" },
  { heading: "Sigmar One", body: "Raleway", category: "premium" },
  { heading: "Signika", body: "Lato", category: "premium" },
  { heading: "Simonetta", body: "Lato", category: "premium" },
  { heading: "Sirin Stencil", body: "Open Sans", category: "premium" },
  { heading: "Six Caps", body: "Droid Sans", category: "premium" },
  { heading: "Skranji", body: "Lato", category: "premium" },
  { heading: "Smokum", body: "Lato", category: "premium" },
  { heading: "Snippet", body: "Lato", category: "premium" },
  { heading: "Snowburst One", body: "Lato", category: "premium" },
  { heading: "Sofadi One", body: "Lato", category: "premium" },
  { heading: "Sofia", body: "Open Sans", category: "premium" },
  { heading: "Sonsie One", body: "Lato", category: "premium" },
  { heading: "Special Elite", body: "Josefin Sans", category: "premium" },
  { heading: "Spicy Rice", body: "Raleway", category: "premium" },
  { heading: "Spinnaker", body: "Lato", category: "premium" },
  { heading: "Spirax", body: "Lato", category: "premium" },
  { heading: "Squada One", body: "Lato", category: "premium" },
  { heading: "Stalinist One", body: "Raleway", category: "premium" },
  { heading: "Stalemate", body: "Lato", category: "premium" },
  { heading: "Stalinist One", body: "Open Sans", category: "premium" },
  { heading: "Stint Ultra Expanded", body: "Lato", category: "premium" },
  { heading: "Stoke", body: "Raleway", category: "premium" },
  { heading: "Strait", body: "Lato", category: "premium" },
  { heading: "Suez One", body: "Lato", category: "premium" },
  { heading: "Sumana", body: "Lato", category: "premium" },
  { heading: "Sunflower", body: "Lato", category: "premium" },
  { heading: "Sunshiney", body: "Lato", category: "premium" },
  { heading: "Supermercado One", body: "Lato", category: "premium" },
  { heading: "Suwannaphum", body: "Lato", category: "premium" },
  { heading: "Swanky and Moo Moo", body: "Lato", category: "premium" },
  { heading: "Syncopate", body: "Lato", category: "premium" },
  { heading: "Tauri", body: "Raleway", category: "premium" },
  { heading: "Teko", body: "Roboto", category: "premium" },
  { heading: "Tenor Sans", body: "Lato", category: "premium" },
  { heading: "The Girl Next Door", body: "Cabin", category: "premium" },
  { heading: "Tienne", body: "Lato", category: "premium" },
  { heading: "Tillana", body: "Lato", category: "premium" },
  { heading: "Timmana", body: "Lato", category: "premium" },
  { heading: "Tinos", body: "Lato", category: "premium" },
  { heading: "Titan One", body: "Raleway", category: "premium" },
  { heading: "Trade Winds", body: "Lato", category: "premium" },
  { heading: "Trirong", body: "Raleway", category: "premium" },
  { heading: "Trocchi", body: "Lato", category: "premium" },
  { heading: "Trykker", body: "Lato", category: "premium" },
  { heading: "Tulpen One", body: "Open Sans", category: "premium" },
  { heading: "Turret Road", body: "Exo 2", category: "premium" },
  { heading: "Ubuntu Condensed", body: "Ubuntu", category: "premium" },
  { heading: "Unica One", body: "Raleway", category: "premium" },
  { heading: "UnifrakturCook", body: "Open Sans", category: "premium" },
  { heading: "Unkempt", body: "Lato", category: "premium" },
  { heading: "Unlock", body: "Raleway", category: "premium" },
  { heading: "Unna", body: "Lato", category: "premium" },
  { heading: "Varta", body: "Raleway", category: "premium" },
  { heading: "Vesper Libre", body: "Lato", category: "premium" },
  { heading: "Vibes", body: "Open Sans", category: "premium" },
  { heading: "Vibur", body: "Lato", category: "premium" },
  { heading: "Vidaloka", body: "Lato", category: "premium" },
  { heading: "Viga", body: "Lato", category: "premium" },
  { heading: "Voces", body: "Lato", category: "premium" },
  { heading: "Volkhov", body: "Lato", category: "premium" },
  { heading: "Vollkorn SC", body: "Lato", category: "premium" },
  { heading: "Voltaire", body: "Raleway", category: "premium" },
  { heading: "Waiting for the Sunrise", body: "Cabin", category: "premium" },
  { heading: "Wallpoet", body: "Open Sans", category: "premium" },
  { heading: "Walter Turncoat", body: "Open Sans", category: "premium" },
  { heading: "Warnes", body: "Lato", category: "premium" },
  { heading: "Wellfleet", body: "Lato", category: "premium" },
  { heading: "Wendy One", body: "Open Sans", category: "premium" },
  { heading: "Wire One", body: "Raleway", category: "premium" },
  { heading: "Xanh Mono", body: "Raleway", category: "premium" },
  { heading: "Yantramanav", body: "Lato", category: "premium" },
  { heading: "Yeseva One", body: "Raleway", category: "premium" },
  { heading: "Yesteryear", body: "Lato", category: "premium" },
  { heading: "Zeyada", body: "Raleway", category: "premium" },
  { heading: "ZCOOL KuaiLe", body: "ZCOOL XiaoWei", category: "premium" },
  { heading: "Zen Dots", body: "Lato", category: "premium" },
  { heading: "Zen Kurenaido", body: "Noto Sans JP", category: "premium" },
  { heading: "Zen Loop", body: "Noto Sans JP", category: "premium" },
  { heading: "Zen Maru Gothic", body: "Noto Sans JP", category: "premium" },
  { heading: "Zilla Slab Highlight", body: "Lato", category: "premium" },
  { heading: "Cinzel", body: "Lato", category: "premium" },
  { heading: "Raleway", body: "Lato", category: "premium" },
  { heading: "Lato", body: "Raleway", category: "premium" },
  { heading: "Lobster", body: "Open Sans", category: "premium" },
  { heading: "Pacifico", body: "Raleway", category: "premium" },
  { heading: "Abril Fatface", body: "Raleway", category: "premium" },
  { heading: "Permanent Marker", body: "Raleway", category: "premium" },
  { heading: "Shadows Into Light", body: "Open Sans", category: "premium" },
  { heading: "Rock Salt", body: "Open Sans", category: "premium" },
  { heading: "Press Start 2P", body: "Roboto Mono", category: "premium" },
  { heading: "Special Elite", body: "Source Sans Pro", category: "premium" },
  { heading: "Stint Ultra Expanded", body: "Roboto", category: "premium" },
  { heading: "Srisakdi", body: "Lato", category: "premium" },
  { heading: "Stalinist One", body: "Roboto Condensed", category: "premium" },
  { heading: "Baloo Chettan 2", body: "Noto Sans Malayalam", category: "premium" },
  { heading: "Baloo Da 2", body: "Lato", category: "premium" },
  { heading: "Baloo Paaji 2", body: "Open Sans", category: "premium" },
  { heading: "Baloo Tamma 2", body: "Lato", category: "premium" },
  { heading: "Baloo Tammudu 2", body: "Lato", category: "premium" },
  { heading: "Baloo Thambi 2", body: "Open Sans", category: "premium" },
  { heading: "Baskervville", body: "Lato", category: "premium" },
  { heading: "Belgrano", body: "Open Sans", category: "premium" },
  { heading: "Bellefair", body: "Raleway", category: "premium" },
  { heading: "Belleza", body: "Lato", category: "premium" },
  { heading: "Bellota", body: "Open Sans", category: "premium" },
  { heading: "BenchNine", body: "Raleway", category: "premium" },
  { heading: "Besley", body: "Lato", category: "premium" },
  { heading: "Beth Ellen", body: "Lato", category: "premium" },
  { heading: "Bigelow Rules", body: "Lato", category: "premium" },
  { heading: "Big Shoulders Display", body: "Big Shoulders Text", category: "premium" },
  { heading: "Big Shoulders Stencil Display", body: "Big Shoulders Text", category: "premium" },
  { heading: "Bilbo Swash Caps", body: "Lato", category: "premium" },
  { heading: "BioRhyme Expanded", body: "BioRhyme", category: "premium" },
  { heading: "Birthstone", body: "Raleway", category: "premium" },
  { heading: "Birthstone Bounce", body: "Raleway", category: "premium" },
  { heading: "Biryani", body: "Open Sans", category: "premium" },
  { heading: "Cormorant Infant", body: "Cormorant", category: "premium" },
  { heading: "Cormorant SC", body: "Cormorant Garamond", category: "premium" },
  { heading: "Cormorant Unicase", body: "Cormorant", category: "premium" },
  { heading: "Cormorant Upright", body: "Cormorant", category: "premium" },
  { heading: "Courgette", body: "Open Sans", category: "premium" },
  { heading: "Covered By Your Grace", body: "Open Sans", category: "premium" },
  { heading: "Crafty Girls", body: "Open Sans", category: "premium" },
  { heading: "Creepster", body: "Open Sans", category: "premium" },
  { heading: "Crete Round", body: "Raleway", category: "premium" },
  { heading: "Croissant One", body: "Open Sans", category: "premium" },
  { heading: "Crushed", body: "Open Sans", category: "premium" },
  { heading: "Cuprum", body: "Open Sans", category: "premium" },
  { heading: "Cute Font", body: "Noto Sans KR", category: "premium" },
  { heading: "Damion", body: "Open Sans", category: "premium" },
  { heading: "Dancing Script", body: "Raleway", category: "premium" },
  { heading: "Dawning of a New Day", body: "Open Sans", category: "premium" },
  { heading: "Days One", body: "Raleway", category: "premium" },
  { heading: "Dekko", body: "Open Sans", category: "premium" },
  { heading: "Dela Gothic One", body: "Noto Sans JP", category: "premium" },
  { heading: "Delius", body: "Open Sans", category: "premium" },
  { heading: "Delius Swash Caps", body: "Open Sans", category: "premium" },
  { heading: "Delius Unicase", body: "Open Sans", category: "premium" },
  { heading: "Della Respira", body: "Raleway", category: "premium" },
  { heading: "Denk One", body: "Open Sans", category: "premium" },
  { heading: "Devonshire", body: "Raleway", category: "premium" },
  { heading: "Dhurjati", body: "Lato", category: "premium" },
  { heading: "Didact Gothic", body: "Open Sans", category: "premium" },
  { heading: "Diplomata", body: "Open Sans", category: "premium" },
  { heading: "Diplomata SC", body: "Open Sans", category: "premium" },
  { heading: "Do Hyeon", body: "Noto Sans KR", category: "premium" },
  { heading: "Dokdo", body: "Noto Sans KR", category: "premium" },
  { heading: "Domine", body: "Raleway", category: "premium" },
  { heading: "Dorsa", body: "Open Sans", category: "premium" },
  { heading: "Dosis", body: "Open Sans", category: "premium" },
  { heading: "DotGothic16", body: "Noto Sans JP", category: "premium" },
  { heading: "Dr Sugiyama", body: "Open Sans", category: "premium" },
  { heading: "Duru Sans", body: "Open Sans", category: "premium" },
  { heading: "Dynalight", body: "Open Sans", category: "premium" },
  { heading: "Eagle Lake", body: "Open Sans", category: "premium" },
  { heading: "East Sea Dokdo", body: "Noto Sans KR", category: "premium" },
  { heading: "Eater", body: "Open Sans", category: "premium" },
  { heading: "El Messiri", body: "Lato", category: "premium" },
  { heading: "Electrolize", body: "Lato", category: "premium" },
  { heading: "Elsie Swash Caps", body: "Open Sans", category: "premium" },
  { heading: "Emblema One", body: "Open Sans", category: "premium" },
  { heading: "Emilys Candy", body: "Open Sans", category: "premium" },
  { heading: "Encode Sans", body: "Encode Sans Expanded", category: "premium" },
  { heading: "Encode Sans Expanded", body: "Encode Sans", category: "premium" },
  { heading: "Encode Sans Semi Condensed", body: "Encode Sans", category: "premium" },
  { heading: "Encode Sans Semi Expanded", body: "Encode Sans", category: "premium" },
  { heading: "Expletus Sans", body: "Raleway", category: "premium" },
  { heading: "Fahkwang", body: "Raleway", category: "premium" },
  { heading: "Farro", body: "Open Sans", category: "premium" },
  { heading: "Faster One", body: "Open Sans", category: "premium" },
  { heading: "Fasthand", body: "Open Sans", category: "premium" },
  { heading: "Federant", body: "Open Sans", category: "premium" },
  { heading: "Federo", body: "Raleway", category: "premium" },
  { heading: "Felipa", body: "Open Sans", category: "premium" },
  { heading: "Fenix", body: "Raleway", category: "premium" },
  { heading: "Finger Paint", body: "Open Sans", category: "premium" },
  { heading: "Finlandica", body: "Lato", category: "premium" },
  { heading: "Fira Sans Condensed", body: "Fira Sans", category: "premium" },
  { heading: "Fira Sans Extra Condensed", body: "Fira Sans", category: "premium" },
  { heading: "Flamenco", body: "Open Sans", category: "premium" },
  { heading: "Flavors", body: "Open Sans", category: "premium" },
  { heading: "Fleur De Leah", body: "Open Sans", category: "premium" },
  { heading: "Fondamento", body: "Open Sans", category: "premium" },
  { heading: "Fontdiner Swanky", body: "Open Sans", category: "premium" },
  { heading: "Forum", body: "Lato", category: "premium" },
  { heading: "Francois One", body: "Raleway", category: "premium" },
  { heading: "Frank Ruhl Libre", body: "Heebo", category: "premium" },
  { heading: "Freckle Face", body: "Open Sans", category: "premium" },
  { heading: "Fredericka the Great", body: "Open Sans", category: "premium" },
  { heading: "Fresca", body: "Open Sans", category: "premium" },
  { heading: "Frijole", body: "Raleway", category: "premium" },
  { heading: "Fruktur", body: "Open Sans", category: "premium" },
  { heading: "Gabriela", body: "Open Sans", category: "premium" },
  { heading: "Gaegu", body: "Noto Sans KR", category: "premium" },
  { heading: "Gafata", body: "Open Sans", category: "premium" },
  { heading: "Galada", body: "Open Sans", category: "premium" },
  { heading: "Galdeano", body: "Raleway", category: "premium" },
  { heading: "Galindo", body: "Raleway", category: "premium" },
  { heading: "Gamja Flower", body: "Noto Sans KR", category: "premium" },
  { heading: "Gayathri", body: "Lato", category: "premium" },
  { heading: "Gelasio", body: "Lato", category: "premium" },
  { heading: "Gemunu Libre", body: "Lato", category: "premium" },
  { heading: "Geostar", body: "Raleway", category: "premium" },
  { heading: "Geostar Fill", body: "Raleway", category: "premium" },
  { heading: "Germania One", body: "Open Sans", category: "premium" },
  { heading: "GFS Neohellenic", body: "Lato", category: "premium" },
  { heading: "Girassol", body: "Lato", category: "premium" },
  { heading: "Glegoo", body: "Raleway", category: "premium" },
  { heading: "Gloria Hallelujah", body: "Open Sans", category: "premium" },
  { heading: "Gluten", body: "Open Sans", category: "premium" },
  { heading: "Goblin One", body: "Open Sans", category: "premium" },
  { heading: "Gochi Hand", body: "Open Sans", category: "premium" },
  { heading: "Goldman", body: "Lato", category: "premium" },
  { heading: "Gorditas", body: "Lato", category: "premium" },
  { heading: "Gothic A1", body: "Noto Sans KR", category: "premium" },
  { heading: "Gotu", body: "Lato", category: "premium" },
  { heading: "Graduate", body: "Raleway", category: "premium" },
  { heading: "Grand Hotel", body: "Lato", category: "premium" },
  { heading: "Grandstander", body: "Open Sans", category: "premium" },
  { heading: "Gravitas One", body: "Open Sans", category: "premium" },
  { heading: "Great Vibes", body: "Open Sans", category: "premium" },
  { heading: "Grechen Fuemen", body: "Lato", category: "premium" },
  { heading: "Grenze", body: "Raleway", category: "premium" },
  { heading: "Grenze Gotisch", body: "Raleway", category: "premium" },
  { heading: "Grey Qo", body: "Raleway", category: "premium" },
  { heading: "Griffy", body: "Open Sans", category: "premium" },
  { heading: "Gudea", body: "Raleway", category: "premium" },
  { heading: "Gurajada", body: "Lato", category: "premium" },
  { heading: "Gupter", body: "Lato", category: "premium" },
  { heading: "Gurajada", body: "Open Sans", category: "premium" },
  { heading: "Habibi", body: "Lato", category: "premium" },
  { heading: "Hammersmith One", body: "Raleway", category: "premium" },
  { heading: "Hanalei Fill", body: "Lato", category: "premium" },
  { heading: "Happy Monkey", body: "Open Sans", category: "premium" },
  { heading: "Harmattan", body: "Lato", category: "premium" },
  { heading: "Headland One", body: "Lato", category: "premium" },
  { heading: "Heebo", body: "Open Sans", category: "premium" },
  { heading: "Henny Penny", body: "Raleway", category: "premium" },
  { heading: "Herr Von Muellerhoff", body: "Open Sans", category: "premium" },
  { heading: "Hi Melody", body: "Noto Sans KR", category: "premium" },
  { heading: "Hina Mincho", body: "Noto Sans JP", category: "premium" },
  { heading: "Hind Guntur", body: "Lato", category: "premium" },
  { heading: "Hind Madurai", body: "Lato", category: "premium" },
  { heading: "Hind Vadodara", body: "Lato", category: "premium" },
  { heading: "Holtwood One SC", body: "Lato", category: "premium" },
  { heading: "Homemade Apple", body: "Open Sans", category: "premium" },
  { heading: "Homenaje", body: "Open Sans", category: "premium" },
  { heading: "Hubballi", body: "Open Sans", category: "premium" },
  { heading: "Hurricane", body: "Lato", category: "premium" },
  { heading: "IBM Plex Mono", body: "IBM Plex Sans", category: "premium" },
  { heading: "Iceberg", body: "Raleway", category: "premium" },
  { heading: "IM Fell Double Pica", body: "Raleway", category: "premium" },
  { heading: "IM Fell English", body: "Open Sans", category: "premium" },
  { heading: "IM Fell French Canon", body: "Open Sans", category: "premium" },
  { heading: "Inika", body: "Open Sans", category: "premium" },
  { heading: "Inknut Antiqua", body: "Lato", category: "premium" },
  { heading: "Inria Sans", body: "Inria Serif", category: "premium" },
  { heading: "Inria Serif", body: "Inria Sans", category: "premium" },
  { heading: "Inspiration", body: "Raleway", category: "premium" },
  { heading: "Inter Tight", body: "Inter", category: "premium" },
  { heading: "Iransans", body: "Lato", category: "premium" },
  { heading: "Irish Grover", body: "Open Sans", category: "premium" },
  { heading: "Island Moments", body: "Open Sans", category: "premium" },
  { heading: "Istok Web", body: "Raleway", category: "premium" },
  { heading: "Italiana", body: "Raleway", category: "premium" },
  { heading: "Italianno", body: "Open Sans", category: "premium" },
  { heading: "Itim", body: "Lato", category: "premium" },
  { heading: "Jacques Francois", body: "Raleway", category: "premium" },
  { heading: "Jacques Francois Shadow", body: "Open Sans", category: "premium" },
  { heading: "Jaldi", body: "Open Sans", category: "premium" },
  { heading: "JetBrains Mono", body: "Fira Sans", category: "premium" },
  { heading: "Jim Nightshade", body: "Raleway", category: "premium" },
  { heading: "Joan", body: "Lato", category: "premium" },
  { heading: "Jomhuria", body: "Open Sans", category: "premium" },
  { heading: "Jomolhari", body: "Open Sans", category: "premium" },
  { heading: "Josefin Sans", body: "Libre Baskerville", category: "premium" },
  { heading: "Josefin Slab", body: "Libre Baskerville", category: "premium" },
  { heading: "Jost", body: "Lato", category: "premium" },
  { heading: "Jua", body: "Noto Sans KR", category: "premium" },
  { heading: "Judson", body: "Raleway", category: "premium" },
  { heading: "Julee", body: "Open Sans", category: "premium" },
  { heading: "Julius Sans One", body: "Raleway", category: "premium" },
  { heading: "Junius", body: "Open Sans", category: "premium" },
  { heading: "Just Another Hand", body: "Open Sans", category: "premium" },
  { heading: "Just Me Again Down Here", body: "Open Sans", category: "premium" },
];

// ── HELPER: pick a random pair ──────────────────────────────
// Optionally exclude specific font names (used for lock logic)
export function getRandomPair(
  excludeHeading?: string,
  excludeBody?: string
): FontPair {
  let candidates = fontPairs;

  // Filter out pairs that would repeat locked fonts
  if (excludeHeading) {
    candidates = candidates.filter((p) => p.heading !== excludeHeading);
  }
  if (excludeBody) {
    candidates = candidates.filter((p) => p.body !== excludeBody);
  }

  // Fallback to full list if filters produce nothing
  if (candidates.length === 0) candidates = fontPairs;

  return candidates[Math.floor(Math.random() * candidates.length)];
}
